# Generated by Django 3.2 on 2021-04-21 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderitem',
            options={'ordering': ['product_name'], 'verbose_name': 'Элемент заказа', 'verbose_name_plural': 'Элементы заказа'},
        ),
        migrations.AlterField(
            model_name='order',
            name='create_date',
            field=models.DateTimeField(db_index=True, verbose_name='Дата'),
        ),
    ]
